Key grabber
christophgysin/pasystray pull request #137
Opened 2021-05-13 11:05 UTC by steelman

I adapted key grabbing code from [pa-applet](https://github.com/fernandotcl/pa-applet). If you think commits should be arranged differently, do tell and I will rearrange them.

2021-05-13 15:28 UTC, christophgysin commented
Can you add guards to make it build against gtk2 and without X11?

2021-05-13 16:34 UTC, steelman commented
Done.

2021-05-13 19:29 UTC, steelman commented
@christophgysin, do you think the key-grabbing command line option should also be under `if defined(HAVE_X11)`?

2021-05-14 07:16 UTC, steelman commented on src/x11_key_grabber.c
> -            XGrabKey(dpy, keycode, Mod2Mask | Mod5Mask | LockMask, root, True, GrabModeAsync, GrabModeAsync);
And I am not entirely sure removing all these is right. (And I am not sure which one to keep) @christophgysin

2021-05-16 06:16 UTC, christophgysin requested changes

2021-05-17 06:22 UTC, christophgysin requested changes

2021-05-17 06:22 UTC, christophgysin commented on src/x11-key-grabber.c
> +                XGrabKey(dpy, keycode, i, root, True, GrabModeAsync, GrabModeAsync);
Instead of grabbing all bit combinations, use `AnyModifier`:
```
XGrabKey(dpy, keycode, AnyModifier, root, True, GrabModeAsync, GrabModeAsync);
```

2021-05-17 10:56 UTC, merged

2021-05-17 10:56 UTC, christophgysin commented
Thanks!

2021-05-17 13:01 UTC, steelman commented
Thank you for the reviews.