[upd] Add a zero-volume indication
christophgysin/pasystray pull request #150
Opened 2021-11-08 21:54 UTC by YanDoroshenko

Not sure this can be merged as is.
audio-volume-zero-symbolic.svg is not included in every icon theme and if it is absent, a placeholder for a missing icon (like a broken image frame) is displayed. Maybe it should be enabled with a feature flag or something?

2021-11-11 19:44 UTC, christophgysin commented
> audio-volume-zero-symbolic.svg is not included in every icon theme

Is there a way to check and dynamically fall back to another icon? If so, I'd be happy to merge this.

2021-11-11 23:11 UTC, YanDoroshenko commented
How does this look? I've restructured fallbacks so that:
* a volume level uses the next one as a fallback
* a mic level uses the next mic level as a fallback and if it's out of mic levels, it tries to use the relevant volume level (with volume level fallbacks)

2021-11-26 12:28 UTC, YanDoroshenko commented
@christophgysin What do you think?

2021-11-27 20:25 UTC, christophgysin requested changes

2021-11-27 20:25 UTC, christophgysin commented on configure.ac
> +AC_INIT([pasystray], [0.9.0], [christoph.gysin@gmail.com], [pasystray],
Don't bump the version.

2021-11-27 20:25 UTC, christophgysin commented on src/ui.c
> +
Don't add empty line.

2021-11-27 20:25 UTC, christophgysin commented on src/ui.c
> +            }
I'm not quite happy with this. There too much special cases and duplication. Also, I don't think it's necessary to have falback for all icons, only for symbolic ones and the *-level-zero ones, which might not be available yet for all users.

Therefore I would suggest to refactor the icon_set_t into a structure that accepts a list of icon, e.g.:
```c
static icon_set_t volume_icon_names = {
    [ICON_IDX_MUTED] = ["audio-volume-muted", NULL],
    [ICON_IDX_ZERO] = ["audio-volume-zero", "audio-volume-muted", NULL],
    [ICON_IDX_LOW] = ["audio-volume-low", NULL],
```
That should then make the implementation a lot more generic again.

2022-04-09 10:40 UTC, closed without merging